version: '2'

volumes:
  mos-config:
  ad-config:
  ha-config:
  z2m-config:
  grocy-config:
  nas-data:
  debuger-git:

networks:
  internal:

services:

  mos:
    container_name: mosquitto
    image: arm32v6/eclipse-mosquitto
    # only allow accessed from localhost
    # ports:
    #   - 8883:8883
    volumes:
      - mos-config:/mosquitto/config
    restart: always
    # network_mode: bridge
    networks:
      internal:

    environment:
      - TZ=Europe/London

  z2m:
    container_name: zigbee2mqtt
    image: benshen98/zigbee2mqtt:1.8.0_armv6
    volumes:
      - z2m-config:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    # network_mode: bridge
    networks:
      internal:
    #     aliases:
    #     - z2m
    privileged: true
    environment:
      - TZ=Europe/London
    depends_on:
      - mos

  ha:
    container_name: home-assistant
    image: homeassistant/raspberrypi2-homeassistant:stable
    ports:
      - 80:8123
    volumes:
      - ha-config:/config
    environment:
      - TZ=Europe/London
    restart: always
    # network_mode: bridge
    networks:
      internal:
    depends_on:
      - mos

  ad:
    container_name: appdaemon
    build:
      dockerfile: AppDaemon.Dockerfile
      context: .
    # network_mode: bridge
    networks:
      internal:
    volumes:
      - ad-config:/conf
    restart: always
    environment:
      - TZ=Europe/London
    depends_on:
      - ha
      - z2m
    # command: ["appdaemon", "-c", "/conf", "-D", "DEBUG"]

  nas:
    container_name: samba
    build:
      dockerfile: nas.Dockerfile
      context: .
    ports:
      - 445:445
    restart: always
    networks:
      internal:
    volumes:
      - nas-data:/data

    environment:
      - TZ=Europe/London

  debuger:
    container_name: vscode
    build:
      dockerfile: debugger.Dockerfile
      context: .
    # network_mode: bridge
    networks:
      internal:
    ports:
      - "22:22"
    volumes:
      - mos-config:/vol/mos-config
      - ad-config:/vol/ad-config
      - ha-config:/vol/ha-config
      - z2m-config:/vol/z2m-config
      - grocy-config:/vol/grocy-config
      - nas-data:/vol/nasdata
      - debuger-git:/vol

  # scanner:
  #   container_name: scanner
  #   build:
  #     dockerfile: scanner.Dockerfile
  #     context: .
  #   networks:
  #     internal:
  #   privileged: true

  grocy:
    image: linuxserver/grocy:arm32v7-latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - grocy-config:/config
    ports:
      - 8000:80
    restart: unless-stopped
