version: '2'

volumes:
  mos-config:
  ad-config:
  ha-config:
  z2m-config:
  grocy-config:
  nas-config:
  nas-data:
  debugger-git:

networks:
  internal:

services:

  mos:
    container_name: mosquitto
    user: 2001:2000
    image: arm32v6/eclipse-mosquitto
    # only allow accessed from localhost, disable port mapping
    # ports:
    #   - 8883:8883
    volumes:
      - mos-config:/mosquitto/config
    restart: always
    networks:
      internal:

    environment:
      - TZ=Europe/London

  z2m:
    user: 2002:dialout
    container_name: zigbee2mqtt
    image: benshen98/zigbee2mqtt:1.8.0_armv6
    volumes:
      - z2m-config:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    networks:
      internal:
    privileged: true
    environment:
      - TZ=Europe/London
    depends_on:
      - mos

  ha:
    # run as root, s6 requires root
    container_name: home-assistant
    image: homeassistant/raspberrypi2-homeassistant:stable
    ports:
      - 80:8123
    volumes:
      - ha-config:/config
    environment:
      - TZ=Europe/London
    restart: always
    networks:
      internal:
    depends_on:
      - mos

  ad:
    user: 2004:2000
    container_name: appdaemon
    build:
      dockerfile: appdaemon/Dockerfile
      context: .
    networks:
      internal:
    volumes:
      - ad-config:/conf
    restart: always
    environment:
      - TZ=Europe/London
    depends_on:
      - ha
      - z2m
    # debugging command
    # command: ["appdaemon", "-c", "/conf", "-D", "DEBUG"]

  nas:
    # requires root to run port 445
    container_name: samba
    build:
      dockerfile: samba/Dockerfile
      context: .
    ports:
      - 445:445
    restart: always
    networks:
      internal:
    volumes:
      - nas-data:/data
      - nas-config:/etc/samba

    environment:
      - TZ=Europe/London

  debugger:
    # NOTE: run as root with sshd (only run under debug mode)
    container_name: debugger
    build:
      dockerfile: debugger/Dockerfile
      context: .
    networks:
      internal:
    ports:
      - "22:22"
    volumes:
      - mos-config:/vol/mos-config
      - ad-config:/vol/ad-config
      - ha-config:/vol/ha-config
      - z2m-config:/vol/z2m-config
      - grocy-config:/vol/grocy-config
      - nas-config:/vol/nas-config
      - nas-data:/vol/nasdata
      - debugger-git:/vol
    restart: no

  # scanner:
  #   container_name: scanner
  #   build:
  #     dockerfile: scanner.Dockerfile
  #     context: .
  #   networks:
  #     internal:
  #   privileged: true

  # grocy:
  #   image: linuxserver/grocy:arm32v7-latest
  #   container_name: grocy
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - grocy-config:/config
  #   ports:
  #     - 8000:80
  #   restart: unless-stopped
